### ISSUE TITLE
Clarify meaning when constraint_sets array is empty

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-receiver-capabilities#14]
Clarify meaning when constraint_sets array is empty, or all constraint sets are marked `meta:enabled: false`.

**Comment by garethsb** [comment]
Three cases to consider:

1. No `constraint_sets`

```json
{
  "caps": {
    "media_types": ["video/raw"]
  }
  ...
}
```

2. Empty `constraint_sets`

_This is currently prohibited by the schemas._ ('minItems' in [constraint_sets.json](https://github.com/AMWA-TV/nmos-receiver-capabilities/blob/v1.0-dev/APIs/schemas/constraint_sets.json))

```json
{
  "caps": {
    "media_types": ["video/raw"],
    "constraint_sets": [
    ],
    "version": "3:1415927"
  }
  ...
}
```

3. All constraint sets disabled

```json
{
  "caps": {
    "media_types": ["video/raw"],
    "constraint_sets": [
      {
        "urn:x-nmos:cap:meta:enabled": false,
        "urn:x-nmos:cap:format:media_type": {
          "enum": ["video/raw"]
        }
      }
    ],
    "version": "3:1415927"
  }
  ...
}
```

_Note, `enum` array is also prohibited from being empty by the schema._

**Comment by garethsb** [comment]
As @jmailhot pointed out in #15, we should also ask "is there a way to _correctly_ signal that a receiver is simply unavailable right now (short of un-registering it entirely)"?

**Comment by garethsb** [comment]
If we were to allow empty `constraint_sets` array, I think  that should evaluate to 'unsatisfied' (`false`) because it's defined as satisfied when **any of** its Constraint Sets are satisfied (an OR operation).

This is the opposite of an empty Constraint Set object, which I think should evaluate to 'satisfied' (`true`) because it's defined to be satisfied when **all of** its Parameter Constraints are satisfied (an AND operation).

I think that `meta:enabled` being `false` means the Constraint Set is 'unsatisfiable', i.e. evaluates to `false` or equivalently is considered removed from the `constraint_sets` list entirely. Thus if all Constraint Sets are disabled, the `constraint_sets` as a whole are unsatisfiable/unsatisfied.

Allowing empty `"constraint_sets": []` would also answer John's last question of how to indicate that the Receiver as a whole is unusable.

**Comment by jmailhot** [comment]
PR #17 covers this matter nicely.
